dataset:
  devset: "dataset/Development_Set"

params:
  sr: 22050
  n_fft: 1024
  hop_len: 256
  n_mels: 128
  fmax: 11025
  segment_len: 0.2

features: ["logmel", "pcen", "melspec"]

train_params:
    n_ways: 10
    k_shots: 5
    optimizer: "Adam"
    lr: 0.001
    weight_decay: 0.1
    epoch: 50
    margin: 0.4
    alpha: 0.5
